### ISSUE TITLE
Error Downloading HIB home

### ISSUE THREAD

**Issue by MarcosCC** [Oblomov/grab-hib#2]
~/HBundle$ ./grab-hib.rb -d whatever > doit
Downloading HIB home ...
Logging in ...
./grab-hib.rb:209:in `download_home': undefined method `field_with' for nil:NilClass (NoMethodError)
        from ./grab-hib.rb:316:in `<main>'

**Comment by Oblomov** [comment]
I'm afraid the Humble guys are making it harder and harder for automatic processing to work. I've pushed an update that might or might not work. Worst case scenario, you can still grab your gamekey list manually by visiting https://www.humblebundle.com/api/v1/user/order and saving the page to disk to feed to `grab-hib` (don't use the `-d` option, just pass the saved orders as argument to the program). This is now documented in the README.

**Comment by MarcosCC** [comment]
So now the error is different (I haven't tried the manual way yet)

~/HBundle$ ./grab-hib.rb -d whatever > doit
/usr/lib/ruby/vendor_ruby/mechanize/http/agent.rb:316:in `fetch': 400 => Net::HTTPBadRequest for https://www.humblebundle.com/login -- unhandled response (Mechanize::ResponseCodeError)
        from /usr/lib/ruby/vendor_ruby/mechanize.rb:562:in `request_with_entity'
        from /usr/lib/ruby/vendor_ruby/mechanize.rb:511:in `post'
        from ./grab-hib.rb:218:in `hib_login'
        from ./grab-hib.rb:344:in `<main>'

**Comment by MarcosCC** [comment]
In Manual mode, all the torrent one show an error, while direct downloads work.

Here an extract showing several torrents failing and a direct download working:

[2016-07-10 09:21:55.088 AWST] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
getting '/home/marcos/HBundle/crusaderkings2/audio/crusaderkingsii_ost_mp3_1377745298.zip' from 'https://dl.humble.com/torrents/crusaderkingsii_ost_mp3_1377745298.zip.torrent?gamekey=SmYkxsVVXctX&ttl=1468200065&t=5a0f82c845e848a915706f2691ae2cc0'
[2016-07-10 09:21:55.104 AWST] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
getting '/home/marcos/HBundle/crusaderkings2/audio/crusaderkingsii_ost_flac_1377745300.zip' from 'https://dl.humble.com/torrents/crusaderkingsii_ost_flac_1377745300.zip.torrent?gamekey=SmYkxsVVXctX&ttl=1468200065&t=64420b62aae139a3340f35ef23f71d9a'
[2016-07-10 09:21:55.120 AWST] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
    magicka
[2016-07-10 09:21:55.132 AWST] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
getting '/home/marcos/HBundle/magicka/audio/magicka_ost_mp3_1377745298.zip' from 'https://dl.humble.com/torrents/magicka_ost_mp3_1377745298.zip.torrent?gamekey=SmYkxsVVXctX&ttl=1468200065&t=bd6956a8fab0e21fac9242d5f6838af3'
[2016-07-10 09:21:55.144 AWST] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
getting '/home/marcos/HBundle/magicka/audio/magicka_ost_flac_1377745298.zip' from 'https://dl.humble.com/torrents/magicka_ost_flac_1377745298.zip.torrent?gamekey=SmYkxsVVXctX&ttl=1468200065&t=22944a3ea209a5fa8cbada739f2b4d74'
[2016-07-10 09:21:55.160 AWST] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server
Manual downloads
getting bridgeconstructor_linux_1390863101.zip from https://dl.humble.com/bridgeconstructor_linux_1390863101.zip?gamekey=nM8APWXFmBK42h3q&ttl=1468200053&t=8515f8878f4c3f454ee616fc70cc048b
--2016-07-10 09:21:55--  https://dl.humble.com/bridgeconstructor_linux_1390863101.zip?gamekey=nM8APWXFmBK42h3q&ttl=1468200053&t=8515f8878f4c3f454ee616fc70cc048b
Resolving dl.humble.com (dl.humble.com)... 205.185.208.62
Connecting to dl.humble.com (dl.humble.com)|205.185.208.62|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48631396 (46M) [application/zip]
Saving to: ‘bridgeconstructor_linux_1390863101.zip’

**Comment by MarcosCC** [comment]
I removed the gamekeys from the above post.

**Comment by Oblomov** [comment]
The transmission error is a different issue altogether. For the future,please open a separate issue.
The script generated by grab-hib uses transmission-remote to control a transmission daemon. If one isn't running, it will fail (yes, I should probably document this better).

**Comment by MarcosCC** [comment]
Sorry, was not sure if ti was related.

Thanks!

**Comment by Oblomov** [comment]
No problem, have fun with your games now ;-)

**Comment by MarcosCC** [comment]
I installed transmission-remote, but did not work (debian). So I tried transmission-daemon, and after setting it to no authentication, this time it all worked. Thanks!
