### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by freizeit-pirat** [Oblomov/grab-hib#3]
Hi there,

thanks a lot for this skript - i've really been looking for this.
I'm absolutly new to ruby, so i had to make ruby installation (2.2.6 on Win10) for this. Also it seemed i had had to install some of the gems from "required" section.

Still after that, when running the script i'm getting a ssl certificate error:

C:\Users\alex\Downloads\grab-hib-master>ruby grab-hib.rb
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:858:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:274:in `fetch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mechanize-2.7.5/lib/mechanize.rb:562:in `request_with_entity'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/mechanize-2.7.5/lib/mechanize.rb:511:in `post'
        from grab-hib.rb:218:in `hib_login'
        from grab-hib.rb:344:in `<main>'

I already tried google-debugging "connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)" but i don't think this is getting me on.

Is there any general requirement for dealing with this cert error?

BR & thanks a lot
Alex

**Comment by Oblomov** [comment]
Hello,

I'm honestly not very familiar with Ruby on Windows, so I can't help directly.

Keep also in mind that the ruby script itself does not download anything: what it does is to generate a shell script to download things via transmission. I'm not sure if this works on Windows at all.
