### ISSUE TITLE
Please help Ruby newbie

### ISSUE THREAD

**Issue by cyotee** [Oblomov/grab-hib#4]
I've been trying to install the required gems with `gem install`. And I tried creating a Gemfile to build it with Bundler. But several of them, pretty much everything from `require set` can't be found in a source. So I figure those are language library files. But even whne I inatall mechanize and nokogiri I get the following error

`$ ./grab-hib.rb -d whatever > doit
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mechanize (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./grab-hib.rb:12:in `<main>'`
Sorry to trouble you with a newb question, and your code obviously work.s What am I missing?

**Comment by Oblomov** [comment]
I'm afraid I cannot be of much help, I'm not familiar with Mac OS X (which is the operating system you seem to be using). The error message indicates that ruby cannot find mechanize, so if you have actually installed it, it might just be that there are multiple versions of ruby in your system and you installed the gem for one, but grab-hib is running in another.

**Comment by cyotee** [comment]
How do I install mechanize? To make sure I did it correctly.

**Comment by Oblomov** [comment]
As I said, I'm not familiar with Mac OS X. I'm afraid I really can't help you with this.
